name: SWPowers
version: '${project.version}'
main: powers.swpowers.SWPowers
api-version: '1.20'
softdepend: [ItemsAdder]

commands:
  powers:
    description: Opens the Force Powers GUI
    usage: /powers

permissions:
  powers.forcepush:
    description: Allows use of Force Push
    default: op
  powers.forcemeditate:
    description: Allows use of Force Meditate
    default: op
  powers.forcelevitate:
    description: Allows use of Force Levitate
    default: op
  powers.forcefreeze:
    description: Allows use of Force Freeze
    default: op
  powers.forcechoke:
    description: Allows use of Force Choke
    default: op
  powers.forcepull:
    description: Allows use of Force Pull
    default: op
  powers.forcemalacia:
    description: Allows use of Force Malacia
    default: op
  powers.darkaura:
    description: Allows use of Dark Aura
    default: op
  powers.forcerepulse:
    description: Allows use of Force Repulse
    default: op
  powers.forcelightning:
    description: Allows use of Force Lightning
    default: op
  powers.electricjudgement:
    description: Allows use of Electric Judgement
    default: op
  powers.forcejump:
    description: Allows use of Double Jump
    default: op